# Generated by Django 4.2.4 on 2023-09-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_version_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='product',
        ),
        migrations.AddField(
            model_name='version',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='versions', to='catalog.product'),
        ),
    ]
